/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  raut.sushant
 * Created: Apr 10, 2020
 */

CREATE TABLE IF NOT EXISTS DOCUMENTTYPE (ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , DOCUMENTTYPE VARCHAR NOT NULL , ACTIVEIND INTEGER NOT NULL  DEFAULT 1);
CREATE TABLE IF NOT EXISTS activation ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"ACTIVATIONKEY" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVATIONDATE" DATETIME  NULL DEFAULT NULL ,"STARTDATE" DATE  NULL DEFAULT NULL ,"ENDDATE" DATE  NULL DEFAULT NULL ,"ACTIVATIONDAYS" INT  NULL DEFAULT NULL ,"ACTIVEIND" INT  NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "appointments" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"DATE" DATE  NOT NULL  ,"SLOTID" INT  NOT NULL  ,"PATIENTID" INT  NOT NULL  ,"DOCTORID" INT  NOT NULL  ,"TREATMENTID" INT  NULL DEFAULT NULL ,"COMMENTS" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"STATUS" INT  NULL DEFAULT NULL ,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "checkup" ("checkUpId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"patientId" INT  NOT NULL  ,"treatment" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"dignosis" TEXT  NULL  COLLATE BINARY,"priscription" TEXT  NULL  COLLATE BINARY,"fees" FLOAT(0,0)  NULL DEFAULT NULL ,"consultantingDoctorFee" FLOAT(0,0)  NULL DEFAULT 0 ,"nextVisitDate" DATETIME  NULL DEFAULT NULL ,"date" DATETIME  NULL DEFAULT NULL ,"dentistName" VARCHAR(50)  NOT NULL  COLLATE BINARY,"refferedBy" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"bp" VARCHAR(10)  NULL DEFAULT 'NULL' COLLATE BINARY,"pulse" VARCHAR(10)  NULL DEFAULT 'NULL' COLLATE BINARY,"weight" VARCHAR(10)  NULL DEFAULT 'NULL' COLLATE BINARY,"activeind" INT  NULL DEFAULT NULL ,CONSTRAINT `FK_checkup` FOREIGN KEY (`patientId`) REFERENCES patients (`PATIENTID`) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS "city" ("cityId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"cityName" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"activeind" INT  NULL DEFAULT NULL );
CREATE TABLE IF NOT EXISTS "clinic" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"ADDRESS" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"CITY" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"CONTACT" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"MORNINGSTARTTIME" TIME  NULL DEFAULT NULL ,"MORNINGENDTIME" TIME  NULL DEFAULT NULL ,"EVENINGSTARTTIME" TIME  NULL DEFAULT NULL ,"EVENINGENDTIME" TIME  NULL DEFAULT NULL ,"ACTIVEIND" INT  NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "doctors" ("DOCTORID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(50)  NOT NULL  COLLATE BINARY,"TYPE" VARCHAR(10)  NOT NULL  COLLATE BINARY,"BIRTHDAY" DATE  NULL DEFAULT NULL ,"GENDER" NVARCHAR(0)  NOT NULL  COLLATE BINARY,"PHOTO" BLOB  NULL  ,"ADDRESS" VARCHAR(60)  NULL DEFAULT NULL COLLATE BINARY,"CITY" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"TELEPHONE" VARCHAR(14)  NULL DEFAULT NULL COLLATE BINARY,"MOBILE" VARCHAR(14)  NULL DEFAULT NULL COLLATE BINARY,"EMAIL" VARCHAR(60)  NULL DEFAULT NULL COLLATE BINARY,"AGE" INT  NOT NULL  ,"DEGREE" VARCHAR(50)  NULL DEFAULT 'null' COLLATE BINARY,"REGISTRATIONNO" VARCHAR(50)  NULL DEFAULT 'null' COLLATE BINARY,"SPECIALIZATION" VARCHAR(50)  NULL DEFAULT 'null' COLLATE BINARY,"ACTIVEIND" INT  NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "employees" ("EMPLOYEEID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(50)  NOT NULL  COLLATE BINARY,"BIRTHDAY" DATE  NULL DEFAULT NULL ,"GENDER" NVARCHAR(0)  NOT NULL  COLLATE BINARY,"PHOTO" BLOB  NULL  ,"ADDRESS" VARCHAR(60)  NULL DEFAULT NULL COLLATE BINARY,"CITY" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"TELEPHONE" VARCHAR(14)  NOT NULL  COLLATE BINARY,"MOBILE" VARCHAR(14)  NULL DEFAULT NULL COLLATE BINARY,"EMAIL" VARCHAR(30)  NULL DEFAULT NULL COLLATE BINARY,"AGE" INT  NULL DEFAULT NULL ,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "expensecategory" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"EXPENSECATEGORY" VARCHAR(30)  NOT NULL  COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "expenses" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"EXPENSECATEGORY" VARCHAR(30)  NOT NULL  COLLATE BINARY,"AMOUNT" INT  NOT NULL  ,"DATE" DATETIME  NOT NULL  ,"NOTES" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVEIND" INT  NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "lab" ("LABID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"CITY" VARCHAR(25)  NULL DEFAULT NULL COLLATE BINARY,"CONTACT" VARCHAR(15)  NULL DEFAULT NULL COLLATE BINARY,"ADDRESS" VARCHAR(25)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "labwork" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"PATIENTID" INT  NOT NULL  ,"CHECKUPID" INT  NOT NULL  ,"LABID" INT  NOT NULL  ,"WORK" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"UL" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,"UR" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,"LL" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,"LR" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,"STATUS" INT  NOT NULL  ,"ACTIVEIND" INT  NOT NULL DEFAULT 1 ,CONSTRAINT `FK_labwork_checkup` FOREIGN KEY (`CHECKUPID`) REFERENCES checkup (`checkUpId`) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT `FK_labwork_lab` FOREIGN KEY (`LABID`) REFERENCES lab (`LABID`) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT `FK_labwork_patient` FOREIGN KEY (`PATIENTID`) REFERENCES patients (`PATIENTID`) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS "labworkname" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(25)  NOT NULL  COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "medicines" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"TYPE" VARCHAR(30)  NOT NULL  COLLATE BINARY,"NAME" VARCHAR(100)  NOT NULL  COLLATE BINARY,"STRENGTH" VARCHAR(10)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVEIND" INT  NULL DEFAULT 1 ,CONSTRAINT `FK_medicines` FOREIGN KEY (`TYPE`) REFERENCES medicinetype (`MEDICINETYPE`) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS "medicinetype" ("MEDICINETYPE" VARCHAR(30) PRIMARY KEY NOT NULL  COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "odontograma" ("cod_odontograma" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"PATIENTID" INT  NULL DEFAULT NULL ,"nome_pac" VARCHAR(60)  NOT NULL  COLLATE BINARY,"18_odon" TEXT  NULL  COLLATE BINARY,"17_odon" TEXT  NULL  COLLATE BINARY,"16_odon" TEXT  NULL  COLLATE BINARY,"15-55_odon" TEXT  NULL  COLLATE BINARY,"14-54_odon" TEXT  NULL  COLLATE BINARY,"13-53_odon" TEXT  NULL  COLLATE BINARY,"12-52_odon" TEXT  NULL  COLLATE BINARY,"11-51_odon" TEXT  NULL  COLLATE BINARY,"41-81_odon" TEXT  NULL  COLLATE BINARY,"42-82_odon" TEXT  NULL  COLLATE BINARY,"43-83_odon" TEXT  NULL  COLLATE BINARY,"44-84_odon" TEXT  NULL  COLLATE BINARY,"45-85_odon" TEXT  NULL  COLLATE BINARY,"46_odon" TEXT  NULL  COLLATE BINARY,"47_odon" TEXT  NULL  COLLATE BINARY,"48_odon" TEXT  NULL  COLLATE BINARY,"28_odon" TEXT  NULL  COLLATE BINARY,"27_odon" TEXT  NULL  COLLATE BINARY,"26_odon" TEXT  NULL  COLLATE BINARY,"65-25_odon" TEXT  NULL  COLLATE BINARY,"64-24_odon" TEXT  NULL  COLLATE BINARY,"63-23_odon" TEXT  NULL  COLLATE BINARY,"62-22_odon" TEXT  NULL  COLLATE BINARY,"61-21_odon" TEXT  NULL  COLLATE BINARY,"71-31_odon" TEXT  NULL  COLLATE BINARY,"72-32_odon" TEXT  NULL  COLLATE BINARY,"73-33_odon" TEXT  NULL  COLLATE BINARY,"74-34_odon" TEXT  NULL  COLLATE BINARY,"75-35_odon" TEXT  NULL  COLLATE BINARY,"36_odon" TEXT  NULL  COLLATE BINARY,"37_odon" TEXT  NULL  COLLATE BINARY,"38_odon" TEXT  NULL  COLLATE BINARY,CONSTRAINT `FK_odontograma` FOREIGN KEY (`PATIENTID`) REFERENCES patients (`PATIENTID`) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS "patients" ("PATIENTID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(50)  NOT NULL  COLLATE BINARY,"CASEID" VARCHAR(10)  NOT NULL  COLLATE BINARY,"BIRTHDAY" DATE  NULL DEFAULT NULL ,"GENDER" NVARCHAR(0)  NOT NULL  COLLATE BINARY,"PHOTO" BLOB  NULL  ,"ADDRESS" VARCHAR(60)  NULL DEFAULT NULL COLLATE BINARY,"CITY" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"TELEPHONE" VARCHAR(14)  NULL DEFAULT NULL COLLATE BINARY,"MOBILE" VARCHAR(14)  NULL DEFAULT NULL COLLATE BINARY,"EMAIL" VARCHAR(60)  NULL DEFAULT NULL COLLATE BINARY,"AGE" INT  NOT NULL  ,"PREMEDICALHISTORY" VARCHAR(200)  NULL DEFAULT NULL COLLATE BINARY,"CREATEDTM" DATETIME  NULL DEFAULT NULL ,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "premedicalhistory" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"DISCRIPTION" VARCHAR(50)  NOT NULL  COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "priscription" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"CHECKUPID" INT  NOT NULL  ,"MEDICINETYPE" VARCHAR(10)  NOT NULL  COLLATE BINARY,"MEDICINENAME" VARCHAR(50)  NOT NULL  COLLATE BINARY,"MEDICINESTRENGTH" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,"FREQUENCY" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,"DURATION" VARCHAR(20)  NULL DEFAULT NULL COLLATE BINARY,CONSTRAINT `FK_priscription_checkup` FOREIGN KEY (`CHECKUPID`) REFERENCES checkup (`checkUpId`) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT `FK_priscription_medicinetype` FOREIGN KEY (`MEDICINETYPE`) REFERENCES medicinetype (`MEDICINETYPE`) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS "referedby" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"NAME" VARCHAR(50)  NOT NULL  COLLATE BINARY,"CITY" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"CONTACT" VARCHAR(15)  NULL DEFAULT NULL COLLATE BINARY,"ADDRESS" VARCHAR(50)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "settings" ("KEYNAME" VARCHAR(50) PRIMARY KEY NOT NULL  COLLATE BINARY UNIQUE,"VALUE" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVEIND" INT  NULL DEFAULT 1 ,"EDITABLE" INT  NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "timeslot" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"START_TIME" TIME  NOT NULL  ,"END_TIME" TIME  NOT NULL  ,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "tokens" ("KEYNAME" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY UNIQUE,"VALUE" VARCHAR(100)  NULL DEFAULT NULL COLLATE BINARY,"ACTIVEIND" INT  NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "treatments" ("treatmentId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"treatmentName" VARCHAR(50)  NOT NULL  COLLATE BINARY,"treatmentDescription" TEXT  NULL  COLLATE BINARY,"treatmentCharges" FLOAT(0,0)  NULL DEFAULT NULL ,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );
CREATE TABLE IF NOT EXISTS "users" ("userId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"name" VARCHAR(45)  NOT NULL  COLLATE BINARY,"loginId" VARCHAR(16)  NOT NULL  COLLATE BINARY,"password" VARCHAR(8)  NOT NULL  COLLATE BINARY,"userType" NVARCHAR(0)  NOT NULL  COLLATE BINARY,"ACTIVEIND" INT  NOT NULL DEFAULT 1 );


CREATE INDEX 'FK_Dentist_checkup' ON 'checkup' (`dentistName` DESC);
CREATE INDEX 'FK_checkup' ON 'checkup' (`patientId` DESC);
CREATE INDEX 'FK_labwork_checkup' ON 'labwork' (`CHECKUPID` DESC);
CREATE INDEX 'FK_labwork_lab' ON 'labwork' (`LABID` DESC);
CREATE INDEX 'FK_labwork_patient' ON 'labwork' (`PATIENTID` DESC);
CREATE INDEX 'FK_medicines' ON 'medicines' (`TYPE` DESC);
CREATE INDEX 'FK_odontograma' ON 'odontograma' (`PATIENTID` DESC);
CREATE INDEX 'FK_priscription_checkup' ON 'priscription' (`CHECKUPID` DESC);
CREATE INDEX 'FK_priscription_medicinetype' ON 'priscription' (`MEDICINETYPE` DESC);

INSERT INTO "main"."city" ("cityId", "cityName", "activeind") VALUES ('1', 'Pune', '1');
INSERT INTO "main"."city" ("cityId", "cityName", "activeind") VALUES ('2', 'Mumbai', '1');

INSERT INTO "main"."DOCUMENTTYPE" ("ID", "DOCUMENTTYPE", "ACTIVEIND") VALUES ('1', 'Reports', '1');
INSERT INTO "main"."DOCUMENTTYPE" ("ID", "DOCUMENTTYPE", "ACTIVEIND") VALUES ('2', 'Photos', '1');
INSERT INTO "main"."DOCUMENTTYPE" ("ID", "DOCUMENTTYPE", "ACTIVEIND") VALUES ('3', 'XRays', '1');

INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('1', 'EMI', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('2', 'Staff Salory', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('3', 'Electricity Bill', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('4', 'Telephone Bill', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('5', 'Rent', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('6', 'Material Bill', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('7', 'Lab bill', '1');
INSERT INTO "main"."expensecategory" ("ID", "EXPENSECATEGORY", "ACTIVEIND") VALUES ('8', 'paper Bill', '1');

INSERT INTO "main"."labworkname" ("ID", "NAME", "ACTIVEIND") VALUES ('1', 'CoCr Crown', '1');
INSERT INTO "main"."labworkname" ("ID", "NAME", "ACTIVEIND") VALUES ('2', 'PFM Crown', '1');
INSERT INTO "main"."labworkname" ("ID", "NAME", "ACTIVEIND") VALUES ('3', 'CoCr FPD', '1');
INSERT INTO "main"."labworkname" ("ID", "NAME", "ACTIVEIND") VALUES ('4', 'PFM FPD', '1');
INSERT INTO "main"."labworkname" ("ID", "NAME", "ACTIVEIND") VALUES ('5', 'Denture', '1');
INSERT INTO "main"."labworkname" ("ID", "NAME", "ACTIVEIND") VALUES ('6', 'RPD', '1');

INSERT INTO "main"."medicinetype" ("MEDICINETYPE", "ACTIVEIND") VALUES ('Cap', '1');
INSERT INTO "main"."medicinetype" ("MEDICINETYPE", "ACTIVEIND") VALUES ('Mouthwash', '1');
INSERT INTO "main"."medicinetype" ("MEDICINETYPE", "ACTIVEIND") VALUES ('Oniment', '1');
INSERT INTO "main"."medicinetype" ("MEDICINETYPE", "ACTIVEIND") VALUES ('Syp', '1');
INSERT INTO "main"."medicinetype" ("MEDICINETYPE", "ACTIVEIND") VALUES ('Tab', '1');
INSERT INTO "main"."medicinetype" ("MEDICINETYPE", "ACTIVEIND") VALUES ('Tooth Paste', '1');

INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('1', 'Diabetic', '1');
INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('2', 'Hypertension', '1');
INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('3', 'Allergy to drug', '1');
INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('4', 'Hypotension', '1');
INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('5', 'Hyper Thyroidism', '1');
INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('6', 'Pregenency', '1');
INSERT INTO "main"."premedicalhistory" ("ID", "DISCRIPTION", "ACTIVEIND") VALUES ('7', 'Lactating Mother', '1');

INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('CLINIC_END_TIME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('CLINIC_NAME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('CLINIC_START_TIME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DOCTOR_DEGREES', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DOCTOR_EMAIL', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DOCTOR_MOBILE', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DOCTOR_NAME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DOCTOR_PRACTICE', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DOCTOR_REGISTRATION_NO', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('EVENING_END_TIME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('EVENING_START_TIME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('MORNING_END_TIME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('MORNING_START_TIME', '', '1', '1');
INSERT INTO "main"."settings" ("KEYNAME", "VALUE", "ACTIVEIND", "EDITABLE") VALUES ('DB_PATH', '', '1', '0');


INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K1', '-98 -81 79 44 -37 -125 -76 -88 119 -87 73 -46 94 66 64 -123 ', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K2', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K3', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K4', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K5', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K6', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K7', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K8', '', '1');
INSERT INTO "main"."tokens" ("KEYNAME", "VALUE", "ACTIVEIND") VALUES ('K9', '', '1');

INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('1', '00:00:00', '00:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('2', '00:15:00', '00:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('3', '00:30:00', '00:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('4', '00:45:00', '01:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('5', '01:00:00', '01:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('6', '01:15:00', '01:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('7', '01:30:00', '01:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('8', '01:45:00', '02:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('9', '02:00:00', '02:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('10', '02:15:00', '02:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('11', '02:30:00', '02:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('12', '02:45:00', '03:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('13', '03:00:00', '03:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('14', '03:15:00', '03:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('15', '03:30:00', '03:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('16', '03:45:00', '04:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('17', '04:00:00', '04:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('18', '04:15:00', '04:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('19', '04:30:00', '04:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('20', '04:45:00', '05:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('21', '05:00:00', '05:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('22', '05:15:00', '05:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('23', '05:30:00', '05:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('24', '05:45:00', '06:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('25', '06:00:00', '06:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('26', '06:15:00', '06:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('27', '06:30:00', '06:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('28', '06:45:00', '07:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('29', '07:00:00', '07:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('30', '07:15:00', '07:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('31', '07:30:00', '07:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('32', '07:45:00', '08:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('33', '08:00:00', '08:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('34', '08:15:00', '08:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('35', '08:30:00', '08:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('36', '08:45:00', '09:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('37', '09:00:00', '09:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('38', '09:15:00', '09:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('39', '09:30:00', '09:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('40', '09:45:00', '10:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('41', '10:00:00', '10:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('42', '10:15:00', '10:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('43', '10:30:00', '10:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('44', '10:45:00', '11:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('45', '11:00:00', '11:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('46', '11:15:00', '11:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('47', '11:30:00', '11:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('48', '11:45:00', '12:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('49', '12:00:00', '12:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('50', '12:15:00', '12:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('51', '12:30:00', '12:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('52', '12:45:00', '13:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('53', '13:00:00', '13:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('54', '13:15:00', '13:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('55', '13:30:00', '13:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('56', '13:45:00', '14:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('57', '14:00:00', '14:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('58', '14:15:00', '14:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('59', '14:30:00', '14:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('60', '14:45:00', '15:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('61', '15:00:00', '15:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('62', '15:15:00', '15:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('63', '15:30:00', '15:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('64', '15:45:00', '16:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('65', '16:00:00', '16:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('66', '16:15:00', '16:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('67', '16:30:00', '16:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('68', '16:45:00', '17:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('69', '17:00:00', '17:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('70', '17:15:00', '17:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('71', '17:30:00', '17:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('72', '17:45:00', '18:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('73', '18:00:00', '18:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('74', '18:15:00', '18:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('75', '18:30:00', '18:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('76', '18:45:00', '19:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('77', '19:00:00', '19:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('78', '19:15:00', '19:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('79', '19:30:00', '19:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('80', '19:45:00', '20:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('81', '20:00:00', '20:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('82', '20:15:00', '20:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('83', '20:30:00', '20:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('84', '20:45:00', '21:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('85', '21:00:00', '21:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('86', '21:15:00', '21:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('87', '21:30:00', '21:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('88', '21:45:00', '22:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('89', '22:00:00', '22:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('90', '22:15:00', '22:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('91', '22:30:00', '22:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('92', '22:45:00', '23:00:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('93', '23:00:00', '23:15:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('94', '23:15:00', '23:30:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('95', '23:30:00', '23:45:00', '1');
INSERT INTO "main"."timeslot" ("ID", "START_TIME", "END_TIME", "ACTIVEIND") VALUES ('96', '23:45:00', '00:00:00', '1');

INSERT INTO "main"."users" ("userId", "name", "loginId", "password", "userType", "ACTIVEIND") VALUES ('1', 'admin', 'admin', 'admin', 'Admin', '1');

INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('1', 'Extraction', 'extraction', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('2', 'X-Ray', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('3', 'Root Canol', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('4', 'Cleaning', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('5', 'Brige', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('6', 'Pulpectomy', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('7', 'Consultation', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('8', 'Denture', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('9', 'CLP', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('10', 'Flap Surgery', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('11', 'Dysimpaction', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('12', 'Filling', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('13', 'RPD', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('14', 'Misc', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('15', 'Crown Cementatin', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('16', 'RCF done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('17', 'POR done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('18', 'BMP Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('19', 'Chechup', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('20', 'BMP Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('21', 'Crawn Prep Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('22', 'RCF Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('23', 'Cyst Removal', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('24', 'Bal Paid', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('25', 'Caries removed & cavit placed', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('26', 'Bal Paid', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('27', 'FPD Cementation done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('28', 'Rx Ortho', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('29', 'Scaling', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('30', 'Closed Dressing Given', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('31', 'Sutute Removal Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('32', 'Repeat Alginate Impressin Made', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('33', 'Adv Given', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('34', 'Surgery', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('35', 'Metapex Pushed cavit placed', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('36', 'DD Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('37', 'Saline Irrigation Done & Cavit Placed', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('38', 'Alginate impression made for RPD', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('39', 'Enameloplasty done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('40', 'Crawn recementation done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('41', 'Ortho ', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('42', 'Ortho Adv', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('43', 'Crawn re cementation done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('44', 'Re RCT', '', '2000.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('45', 'Saline Irrigatin done & open dressing given', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('46', 'Apicetomy', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('47', 'Debonding & Scaling Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('48', 'ReRC started', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('49', 'LA given bt  Extraction not done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('50', 'Post Placed & por done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('51', 'Temp Crawn cemented ', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('52', 'Scaling & Polishing Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('53', 'Coping Trial Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('54', 'Highpoint Reduced', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('55', 'Caries Removed & cottan placed', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('56', 'PI taken', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('57', 'Bordermouldind done & FI Taken', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('58', 'Byte Taken', '', '0.0', '0');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('59', 'Trying Done', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('60', 'JR recorded', '', '0.0', '1');
INSERT INTO "main"."treatments" ("treatmentId", "treatmentName", "treatmentDescription", "treatmentCharges", "ACTIVEIND") VALUES ('61', 'Alveoloplast Done', '', '0.0', '1');

